### ISSUE TITLE
update

### ISSUE THREAD

**Issue by wanzhixiao** [twitter-research/sign#3]
Hi,thanks for your greate work! have any plan to upload the remain code?

**Comment by Noired** [comment]
Hi wanzhixiao!
We may upload additional code later on, but we are not planning any immediate release at the moment.
We invite you to also explore the implementation of SIGN in [PyTorch Geometric](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/transforms/sign.py) and [DeepGraphLibrary](https://github.com/dmlc/dgl/blob/master/examples/pytorch/ogb/sign/sign.py).

All the best!
