### ISSUE TITLE
The code is different from the paper

### ISSUE THREAD

**Issue by hazdzz** [twitter-research/sign#6]
In the paper, GCN-normalized, PPR-based, and triangle-based adjacency matrices are utilized, but I cannot find those adjacency matrices in the code. Would you update code as the implementation of the paper?

**Comment by ayeshasiddika9196** [comment]
**403**

**Comment by venomouscyanide** [comment]
@hazdzz I see the issue is closed. However, I was wondering if you got access to the operators described in the paper anywhere? I still find it in the codebase anywhere.
